import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

	const testPostMethod1 = async () => {
		fetch('https://jsonplaceholder.typicode.com/posts', {
			method: 'POST',
			body: JSON.stringify({
				title: 'foo',
				body: 'bar',
				userId: 1,
			}),
			headers: {
				'Content-type': 'application/json; charset=UTF-8',
			},
		})
			.then((response) => response.json())
			.then((json) => console.log(json))
	}

	const testPostMethod2 = async () => {
		fetch('/api/hello')
			.then((response) => response.json())
			.then((json) => console.log(json))
	}

	const testPostMethod3 = async () => {
		try {
			console.log('testPostMethod3')
			const data = {
				name: 'jeanquark3',
			}
			const response = await fetch('/api/test1/', {
				method: 'POST',
				headers: {
					'Content-type': 'application/json',
				},
				body: JSON.stringify(data)
			})
			const json = await response.json()
			console.log('json: ', json)
		} catch (error) {
			console.log('error: ', error)
		}
	}

	const testPostMethod3_1 = async () => {
		fetch('/api/test3/', {
			method: 'POST',
			body: JSON.stringify({
				name: 'jeanquark3',
			}),
			mode: 'cors',
			headers: {
				'Content-type': 'application/json; charset=UTF-8',
			}
		})
			.then((response) => response.json())
			.then((json) => console.log(json))
	}

	const testPostMethod4 = async () => {
		try {
			console.log('testPostMethod4')
			const data = {
				name: 'jeanquark4',
			}
			const response = await fetch('/api/test4/', {
				method: 'POST',
				headers: {
					'Content-type': 'application/json',
				},
				body: JSON.stringify(data)
			})
			const json = await response.json()
			console.log('json: ', json)
		} catch (error) {
			console.log('error: ', error)
		}
	}

	const testPostMethod5 = async () => {
		console.log('testPostMethod5')
		const response = await fetch('/api/test5/', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json; charset=UTF-8',
			}
		})
		console.log('response: ', response)
		const json = await response.json()
		console.log('json: ', json)
	}

	const testPostMethod6 = async () => {
		console.log('testPostMethod6')
		const data = {
			name: 'jeanquark6',
		}
		const response = await fetch('/api/test6/', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json; charset=UTF-8',
			},
			body: JSON.stringify(data),
		})
		console.log('response: ', response)
		const json = await response.json()
		console.log('json: ', json)
	}

	const testPostMethod7 = async () => {
		console.log('testPostMethod7')
		const data = {
			name: 'jeanquark7',
		}
		const response = await fetch('/api/test7/', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json; charset=UTF-8',
			},
			body: JSON.stringify(data),
		})
		console.log('response: ', response)
		const json = await response.json()
		console.log('json: ', json)
	}

	const testPostMethod8 = async () => {
		console.log('testPostMethod8')
		const data = {
			name: 'jeanquark8',
		}
		const response = await fetch('https://thisisfan.com/api/test7/', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json; charset=UTF-8',
			},
			body: JSON.stringify(data),
		})
		console.log('response: ', response)
		const json = await response.json()
		console.log('json: ', json)
	}

	const testPostMethod9 = async () => {
		let formData = new FormData();
		formData.append('name', 'jeanquark9');

		const response = await fetch("api/test9/",
			{
				body: formData,
				method: "post"
			});
		console.log('response: ', response);
		const json = await response.json()
		console.log('json: ', json);
	}

	const testPostMethod10 = async () => {
		const response = await fetch('/api/test10/', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json; charset=UTF-8',
			},
			body: JSON.stringify({
				name: 'jeanquark10'
			})
		})
		console.log('response: ', response);
		const json = await response.json()
		console.log('json: ', json);
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>

				<br /><br />

				<button onClick={() => testPostMethod1()}>testPostMethod1 (POST /jsonplaceholder)</button><br />
				<button onClick={() => testPostMethod2()}>testPostMethod2 (GET api/hello)</button><br />
				<button onClick={() => testPostMethod3()}>testPostMethod3 (POST api/test1)</button><br />
				<button onClick={() => testPostMethod4()}>testPostMethod4 (POST api/test4)</button><br />

				<br />
				<h4>Last deployment: Friday 14:00</h4>
			</main>


		</div>
	)
}
